#' @title Generate deaths (kill the minnow)
#' @description This function generates a vector of deaths (binary variable) based on an input vector of probabilities of occurence
#' @param prob	Probability of occurence. Generated by *suitability*
#' @export
#' @author Martin Sullivan

generate_death<-function(prob){
  as.numeric(prob<=runif(length(prob)))
}
