#' @title Generate gulps
#' @description This function generates a vector of counts of stress gulps based on an input vector of probabilities of occurence
#' @param prob	Probability of occurence. Generated by *suitability*
#' @param stock Level of stocasticity (sd of rnorm)
#' @export
#' @author Martin Sullivan

generate_gulp<-function(prob,stock=0){
  gs<-3*(1-prob)+5*(1-prob)+rnorm(length(prob),stock)
  gs[gs<0]<-0
  round(gs)
}
