#' @title Generate presences
#' @description This function generates a vector of presences and absences based on an input sequence of probabilities of occurence
#' @param prob	Probability of occurence. Generated by *suitability*
#' @export
#' @author Martin Sullivan

generate_presence<-function(prob){
  as.numeric(prob>=runif(length(prob)))
}