#' @title Simulate data based on a study design
#' @description This function takes takes a study design generated by *design_study* and simulates data that would be collected using it.
#' Note - if you have chosen both an experiment and a field study, *design_study* will return a list. *simulate_data* will take that list, and return a list in turn.
#' @param env Explanatory variables sampled by the study design. Produced by *design_study*.
#' @export
#' @author Martin Sullivan


simulate_data<-function(env){
  ps<-c(-10,3,-0.3,5,-0.6,-0.02)
  exp.obs<-c()
  field.obs<-c()
  if(!is.null(env[[1]])){
    exp.obs<-behaviour_experiment(env[[1]],ps)
  }
  if(!is.null(env[[2]])){
    PA<-generate_presence(suitability(env[[2]][,1],env[[2]][,2],FALSE,ps[1],ps[2],ps[3],ps[4],ps[5],ps[6]))
    field.obs<-cbind(env[[2]],PA)
  }
  list(exp.obs,field.obs)
}




